docker push your_dockerhub_username/embedding:latest
docker push your_dockerhub_username/vector_db:latest
docker push your_dockerhub_username/retriever:latest
docker push your_dockerhub_username/re_ranker:latest
docker push your_dockerhub_username/agent:latest
docker push your_dockerhub_username/api_gateway:latest
