apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: embedding
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: retriever-service
spec:
  selector:
    app: retriever
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: re-ranker-service
spec:
  selector:
    app: re-ranker
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
spec:
  selector:
    app: agent
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: vector-db-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: vector-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: chroma-db-service
spec:
  selector:
    app: chroma-db
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
