name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Embedding Module
        uses: docker/build-push-action@v2
        with:
          context: ./embedding
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/embedding:latest

      - name: Build and push Retriever Module
        uses: docker/build-push-action@v2
        with:
          context: ./retriever
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/retriever:latest

      - name: Build and push Re-ranker Module
        uses: docker/build-push-action@v2
        with:
          context: ./re_ranker
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/re_ranker:latest

      - name: Build and push Agent Module
        uses: docker/build-push-action@v2
        with:
          context: ./agent
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/agent:latest

      - name: Build and push API Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./api_gateway
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api_gateway:latest

      - name: Build and push Vector DB Module
        uses: docker/build-push-action@v2
        with:
          context: ./vector_db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vector_db:latest
