name: CI/CD Pipeline

on:
  push:
    branches: [main]
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Embedding Module
        uses: docker/build-push-action@v2
        with:
          context: ./embedding
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/embedding:latest

      - name: Build and push Retriever Module
        uses: docker/build-push-action@v2
        with:
          context: ./retriever
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/retriever:latest

      - name: Build and push Re-ranker Module
        uses: docker/build-push-action@v2
        with:
          context: ./re_ranker
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/re_ranker:latest

      - name: Build and push Agent Module
        uses: docker/build-push-action@v2
        with:
          context: ./agent
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/agent:latest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./api_gateway
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api_gateway:latest

      - name: Build and push Vector DB Module
        uses: docker/build-push-action@v2
        with:
          context: ./vector_db
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vector_db:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name rag-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml

      - name: Update EKS
        run: |
          kubectl rollout restart deployment/retriever
          kubectl rollout restart deployment/re-ranker
          kubectl rollout restart deployment/agent
          kubectl rollout restart deployment/api-gateway
          kubectl rollout restart deployment/vector-db
